### PR TITLE
feat(Project resources): Definition and Implementations are now .xml files

### LINKED ISSUE #33: Generated definition and implementation resources files are unclear
**Is your feature request related to a problem? Please describe.**
when using this archetype, generated files don't follow same pattern as in studio

**Describe the solution you'd like**
since those two files are `.xml` files, i'd like to just have `definition.xml` and `implementation.xml`resoursource file, so i can benefit from xml IDE completion feature based on provided XSD
then build step should apply replacements and rename as expected in studio aka `<definitionId>-<definitionVersion>.def` and `<implementationId>-<implementationVersion>.impl`. definition Id and implementation Id may be just the archetype id (in the maven way 

**Describe alternatives you've considered**
i did a manual update of generated files in order to make the connector work as expected in the studio (7.10.1 EE version)

**Additional context**
seem BCD can't deploy and enable process as expected (in same version)

### PR DESCRIPTION
**Pull request by alachambre**
* In order to ease the project edition in classic development
environments, the definition and implementation files now have the xml
extension (previously .def and .impl). Thus, the matching between the xml file
and its xsd is automatically performed by the IDE.
* At build time, definition and implementation files are renamed with
their original extension, so the Bonita engine can use them.

Closes #33

### CODE REVIEW

**Comment by uguy** [comment]
Hi there, 
Not really found of renaming file extensions because of bad tooling support :/
It can be really confusing for people to work and deploy property files with different extensions.
I suppose it's not that difficult to associate file ext and format in IDE.

In case you still want to use xml and rename files, you don't need any other maven plugin to do that. Maven assembly plugin can do the jobs (<destName> prop)

**Comment by alachambre** [comment]
Well apparently it's harder on itellij than on eclipse (based on Laurent feedback). 
An other idea that came up to my mind was to deliver an eclipse plugin to allows the edition of def and impl file with a proper graphical interface, but once again nothing for intellij users (as far as I know)

**Comment by uguy** [comment]
For Intellij user, they can go to settings > file types and register new patterns for XML syntax :
- `*connector*.def`
- `*connector*.impl`

This won't break other association (like kotlin/cnative for `.def` file) and show bonita files as XML files editor.

**Comment by uguy** [comment]
Closing the issue as won't fix as discussed by the team. Users should rely on better IDE support.

**Pull request closed without merging**
